.TH "com.cassandra.TrialWithIText.NavbarPDF" 3 "Wed Mar 10 2021" "TrialWithItext" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.cassandra.TrialWithIText.NavbarPDF
.SH SYNOPSIS
.br
.PP
.PP
Inherits PdfPage\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "PdfImageXObject \fBpdfToThumbnailImg\fP (PdfDocument pdf)  throws java\&.io\&.IOException "
.br
.ti -1c
.RI "void \fBImgtoStack\fP (PdfImageXObject img)"
.br
.ti -1c
.RI "void \fBnavBar\fP (Image[] stack)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBNavbarPDF\fP (PdfDocument pdfDocument)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file NavbarPDF\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "com\&.cassandra\&.TrialWithIText\&.NavbarPDF\&.NavbarPDF (PdfDocument pdfDocument)\fC [protected]\fP"

.PP
Definition at line 20 of file NavbarPDF\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void com\&.cassandra\&.TrialWithIText\&.NavbarPDF\&.ImgtoStack (PdfImageXObject img)"

.PP
Definition at line 34 of file NavbarPDF\&.java\&.
.SS "void com\&.cassandra\&.TrialWithIText\&.NavbarPDF\&.navBar (Image[] stack)"

.PP
Definition at line 37 of file NavbarPDF\&.java\&.
.SS "PdfImageXObject com\&.cassandra\&.TrialWithIText\&.NavbarPDF\&.pdfToThumbnailImg (PdfDocument pdf) throws java\&.io\&.IOException"

.PP
Definition at line 24 of file NavbarPDF\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TrialWithItext from the source code\&.
