.TH "com.cassandra.TrialWithIText.ExtractCode" 3 "Wed Mar 10 2021" "TrialWithItext" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.cassandra.TrialWithIText.ExtractCode
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file ExtractCode\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static void com\&.cassandra\&.TrialWithIText\&.ExtractCode\&.main (String[] args)\fC [static]\fP"

.PP
Definition at line 5 of file ExtractCode\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TrialWithItext from the source code\&.
