.TH "com.cassandra.TrialWithIText.App" 3 "Wed Mar 10 2021" "TrialWithItext" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.cassandra.TrialWithIText.App
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBcreatePdf\fP (String dest)  throws IOException, java\&.io\&.IOException "
.br
.ti -1c
.RI "void \fBcreateNewPDF\fP (String src)  throws java\&.io\&.IOException "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)  throws IOException     "
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fBDEST\fP = 'results/chapter01/practice2\&.pdf'"
.br
.ti -1c
.RI "static final String \fBSRC1\fP = 'results/chapter01/practice1\&.pdf'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Hello world! 
.PP
Definition at line 27 of file App\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void com\&.cassandra\&.TrialWithIText\&.App\&.createNewPDF (String src) throws java\&.io\&.IOException"

.PP
Definition at line 80 of file App\&.java\&.
.SS "void com\&.cassandra\&.TrialWithIText\&.App\&.createPdf (String dest) throws IOException, java\&.io\&.IOException"

.PP
Definition at line 49 of file App\&.java\&.
.SS "static void com\&.cassandra\&.TrialWithIText\&.App\&.main (String[] args) throws IOException\fC [static]\fP"

.PP
Definition at line 33 of file App\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String com\&.cassandra\&.TrialWithIText\&.App\&.DEST = 'results/chapter01/practice2\&.pdf'\fC [static]\fP"

.PP
Definition at line 29 of file App\&.java\&.
.SS "final String com\&.cassandra\&.TrialWithIText\&.App\&.SRC1 = 'results/chapter01/practice1\&.pdf'\fC [static]\fP"

.PP
Definition at line 30 of file App\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TrialWithItext from the source code\&.
