.TH "NavBar" 3 "Wed Mar 10 2021" "TrialWithItext" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NavBar \- Navigation Pane
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcom\&.cassandra\&.TrialWithIText\&.UINavigationPane\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Here starts the navigation Pane creation or formation 
.SH "Author"
.PP 
Generated automatically by Doxygen for TrialWithItext from the source code\&.
